spring:
  config:
    import: usersecrets.yml

  sql:
    init:
      mode: embedded

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  data:
    rest:
      base-path: /api
      return-body-on-create: true
      return-body-on-update: true

logging:
  level:
    root: INFO
    # show application of sql database initialization scripts
    org.springframework.jdbc.datasource.init.ScriptUtils: INFO
    # show bind parameters
    # org.hibernate.type.descriptor.sql: TRACE
