shopocon:
  security:
    profile: dev
    origins: [ http://localhost:4200 ]
    jwt:
      access-token-cookie-name: AuthToken
      refresh-token-cookie-name: RefreshToken
      secret: shopoconJwtSecretKey
      access-token-expiration-min: 30
      refresh-token-expiration-min: 1440
  catalog:
    low-stock-boundary: 5

spring:
  config:
    import: usersecrets.yml

  sql:
    init:
      mode: embedded

  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  data:
    rest:
      base-path: /api
      return-body-on-create: true
      return-body-on-update: true

  session:
    store-type: hazelcast
    hazelcast:
      map-name: 'shopocon:session:sessions'

server:
  servlet:
    session:
      cookie:
        http-only: true
        #secure: true
      timeout: 20m

logging:
  level:
    root: WARN
    # show application of sql database initialization scripts
    #org.springframework.jdbc.datasource.init.ScriptUtils: INFO
    # show bind parameters
    #org.hibernate.type.descriptor.sql: TRACE
